version: '3'
services:

  book_catalog: 
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
     - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://anjo:Two8BAo0YPl0tGtkFVPrgcmW314hQMdC@dpg-crjuu3qj1k6c73fqh6b0-a.oregon-postgres.render.com/pgsql_ruhz
    restart: "no"

  inventory_management:
    image: inventory-management   
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8001:8001"
    environment:
     - DATABASE_URL=postgresql://anjo:Two8BAo0YPl0tGtkFVPrgcmW314hQMdC@dpg-crjuu3qj1k6c73fqh6b0-a.oregon-postgres.render.com/pgsql_ruhz
    restart: "no"

    