# Deployment for book-catalog
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: sit722week7anjo.azurecr.io/book:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://anjo:Two8BAo0YPl0tGtkFVPrgcmW314hQMdC@dpg-crjuu3qj1k6c73fqh6b0-a.oregon-postgres.render.com/pgsql_ruhz"

---
# Service for book-catalog
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
# Deployment for inventory-management
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: sit722week7anjo.azurecr.io/inventory:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          value: "postgresql://anjo:Two8BAo0YPl0tGtkFVPrgcmW314hQMdC@dpg-crjuu3qj1k6c73fqh6b0-a.oregon-postgres.render.com/pgsql_ruhz"

---
# Service for inventory-management
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
